services:
  demo-nginx:
    build:
      context: ../app
    image: opslab-demo:latest
    container_name: opslab-demo
    ports:
      - "8080:80"
    volumes:
      - ../app:/usr/share/nginx/html:ro
    restart: unless-stopped
